---
- hosts: {{ instance_name }}
  gather_facts: False
  connection: ssh
  user: ubuntu
  sudo: yes
  vars:
    server_network: {{ server_network }}
    is_persistent: {{ is_persistent }}
    vpn_subnet: {{ vpn_subnet }}
    clients_can_see_each_other: {{ clients_can_see_each_other }}
    port_number: {{ port_number }}
    protocol: {{ protocol }}
    pki_dir: {{ pki_dir }}

  roles:
    - openvpn
