---

- name: install openvpn
  apt: name=openvpn state=present update_cache=yes

- name: make sure /opt/openvpn exists
  file: path=/opt/openvpn state=directory

- name: make sure directory for this server exists
  file: path={{ pki_dir }} state=directory

- name: get server key
  copy: src={{ pki_dir }}/private/server.key dest={{ pki_dir }}/server.key
  notify:
  - restart openvpn

- name: get server crt
  copy: src={{ pki_dir }}/issued/server.crt dest={{ pki_dir }}/server.crt
  notify:
  - restart openvpn

- name: get ca crt
  copy: src={{ pki_dir }}/ca.crt dest={{ pki_dir }}/ca.crt
  notify:
  - restart openvpn

- name: get crl
  copy: src={{ pki_dir }}/crl.pem dest={{ pki_dir }}/crl.pem

- name: get dh
  copy: src={{ pki_dir }}/dh.pem dest={{ pki_dir }}/dh.pem
  notify:
  - restart openvpn

- name: write config
  template: src=server.conf.j2 dest={{ pki_dir }}/server.conf owner=root group=root
  notify:
  - restart openvpn
